### ISSUE TITLE
Android architecture: arm64-v8

### ISSUE THREAD

**Issue by redfast00** [kost/NetworkMapper#15]
NetworkManager doesn't download correct binary (Cyanogenmod 13 on OnePlus Two)

**Comment by kost** [comment]
Thanks for your report. Which one did it download? Could you copy&paste from the window?

**Comment by kost** [comment]
I'm working on it and it seems it is working. Could you test it and let me know? 

You need to go to the Settings and Change URL to the following (for the test):
https://github.com/kost/nmap-android/releases/download/v7.25BETA2and1

I think this URL should work as well:
https://github.com/kost/nmap-android/releases/download/v7.25BETA2and4

If you think you can help me testing, I have bunch of release URLs here:
https://github.com/kost/nmap-android/releases

It would be helpful for me to tell me which version works for you. 

Thanks in advance!

**Comment by redfast00** [comment]
I re-installed NetworkManager (1.7) from F-Droid and it successfully downloaded the correct binary (`nmap-7.12-binaries-arm64-v8a.zip`) without any changes in the settings. I just scanned a target and it worked. Thanks a lot for the bugfix!
