### ISSUE TITLE
  Move data folder from userspace to Android/data

### ISSUE THREAD

**Issue by agilob** [kost/NetworkMapper#8]
Currently downloaded data is saved under `/storage/emulated/0/Android/opt/` after uninstalling application the data is not removed. If data would be stored under /storage/emulated/0/Android/data/org.kost.nmap.android.networkmapper it would be removed with application and would be hidden from user.

Use the following code to get proper directory data:

```
Log.i(TAG, getExternalFilesDir(null).getAbsolutePath());
/storage/emulated/0/Android/data/app.id/files
```

[All apps (root or not) have a default data directory, which is /data/data/. By default, the apps databases, settings, and all other data go here. If an app expects huge amounts of data to be stored, or for other reasons wants to "be nice to internal storage", there's a corresponding directory on the SDCard (Android/data/)](http://android.stackexchange.com/questions/47924/where-android-apps-store-data/47951#47951)

**Comment by kost** [comment]
Thanks for nice suggestion. This looks as good suggestion. Why I was thinking about /sdcard/opt is that users could have their custom NSEs inside dir, so maybe they don't want to loose them. 

Anyway, I will try to work it out in next nmap binary release and NetworkMapper release. it's not that easy to make this change as I have to compile nmap with different dir for every platform (so users don't have to type nmap --data-dir /storage/emulated/0/Android/data/org.kost.nmap.android.networkmapper). It would be clumsy to type it every type for mobile users.

But, first, this is something we have to decide: is /sdcard/opt/ or /storage/emulated/0/Android/data/org.kost.nmap.android.networkmapper  better...

**Comment by agilob** [comment]
> But, first, this is something we have to decide: is /sdcard/opt/ or /storage/emulated/0/Android/data/org.kost.nmap.android.networkmapper better... 

This Environment path is device dependent, on my tablet I have /storage/emulated/0/, on my phone CM11 it's /storage/sdcard0/0/ (dont know why builtin memory is detected as SDcard).
