### ISSUE TITLE
copy output to clipboard

### ISSUE THREAD

**Issue by Hauwertlhaufn** [kost/NetworkMapper#9]
A option to copy the output to the clipboard would be very nice.

**Comment by kost** [comment]
Hello and thanks for your suggestion.

Implemented in https://github.com/kost/NetworkMapper/commit/d6944757719f9cbd446d264ef25004c46b990956

After testing, it will be released in next version of the app. 

Happy scanning!

**Comment by Hauwertlhaufn** [comment]
Thank you :thumbsup:
